#! /bin/bash

if [[ -z $1 || -z $2 || -z $3 ]];
then
	echo "addd <filename> <entryname> <cmd>"
else

	desktop_file="$HOME/.local/share/applications/${1}.desktop"

	touch $desktop_file
	> $desktop_file

	echo "[Desktop Entry]" 		>> $desktop_file
	echo "Version=1.0"			>> $desktop_file 
	echo "Type=Application"		>> $desktop_file
	echo "Name=$2"				>> $desktop_file
	echo "Exec=$3"				>> $desktop_file

	echo "PATH: $desktop_file"
	echo "NAME: $2"
	echo "CMD:  $3"
fi
