#! /bin/bash

name="$1"

if ! i3-msg "[title=\"$name\"] scratchpad show";
then
	if [ "$name" != "terminal" ];
	then
		i3-msg "exec --no-startup-id \"alacritty -t $name --class _scratchpad -e $@\""
	else
		i3-msg "exec --no-startup-id \"alacritty -t $name --class _scratchpad\""
	fi

	sleep 0.08;
	xprop -name $name -f _NET_WM_STATE 32a -set _NET_WM_STATE _NET_WM_STATE_SKIP_TASKBAR
fi

