#!/bin/bash

MENU="$(rofi -sep "|" -dmenu -i -p '' -yoffset -20 -location 5 -lines 6 -width 10 -bw 0 <<< "Lock|Suspend|Hibernate|Logout|Reboot|Shutdown")"
case "$MENU" in
	*Lock) lock ;;
	*Suspend) lock && systemctl suspend ;;
	*Hibernate) lock && systemctl hibernate ;;
	*Logout) i3-msg exit ;;
	*Reboot) systemctl reboot ;;
	*Shutdown) systemctl poweroff -i
esac
