#! /bin/bash

# $1 		--> corner number
# $X		--> window X coordinate 
# $Y 		--> window Y coordinate
# $WIDTH	--> window width
# $HEIGHT	--> window height
# $SCREEN	--> screen number
# $WINDOW	--> window id

#  +=================+ <-- tint2 bar
#  |7       8       9|	
#  |                 |
#  |4       5       6|
#  |                 |
#  |1       2       3|
#  +=================+ <-- polybar

if test "$(xwininfo -name tint | grep "Map State" | awk '{ print $3 }')" != "IsViewable";
then
	tint_h=0
else
	tint_h=20
fi
if test "$(xwininfo -name "polybar_mob" | grep "Map State" | awk '{ print $3 }')" != "IsViewable";
then
	polybar_h=0
else
	polybar_h=20
fi


eval $(xdotool getactivewindow getwindowgeometry --shell)

win_border=$(xwininfo -id $WINDOW | grep "Relative upper-left X" | awk '{ print $4 }')
h_win_w=$(( $WIDTH / 2 ))
h_win_h=$(( $HEIGHT / 2 ))

screen_w=$(xdpyinfo | grep dimensions | awk ' { print $2; }' | tr "x" "\n" | head -n1)
screen_h=$(xdpyinfo | grep dimensions | awk ' { print $2; }' | tr "x" "\n" | tail -n1)

h_screen_w=$(( $screen_w / 2 ))
h_screen_h=$(( $screen_h / 2 ))

left=$win_border
center_w=$(( $h_screen_w - $h_win_w))
right=$(( $screen_w - $WIDTH - $win_border ))

top=$(( $win_border + $tint_h ))
center_h=$(( $h_screen_h - $h_win_h ))
bottom=$(( $screen_h - $HEIGHT - $win_border - $polybar_h ))

case "$1" in
		1) xdotool getactivewindow windowmove $left $bottom; 
				;;
		2) xdotool getactivewindow windowmove $center_w $bottom
				;;
		3) xdotool getactivewindow windowmove $right $bottom
				;;
		4) xdotool getactivewindow windowmove $left $center_h
				;;
		5) xdotool getactivewindow windowmove $center_w $center_h
				;;
		6) xdotool getactivewindow windowmove $right $center_h
				;;
		7) xdotool getactivewindow windowmove $left $top
				;;
		8) xdotool getactivewindow windowmove $center_w $top
				;;
		9) xdotool getactivewindow windowmove $right $top
				;;
esac
