#! /bin/bash

list_path="/tmp/xhide_list"

IFS=$'\n' read -d '' -r -a IDs < $list_path

if test "${#IDs[@]}" != "0";
then
	if test "$1" = "-pop";
	then
		lastrow=$(tail -1 $list_path)
		#xdotool windowactivate $lastrow
		xdotool windowmap $lastrow
		head -n -1 $list_path > /tmp/xhide_list.tmp ; mv /tmp/xhide_list.tmp $list_path
	else
		for index in "${!IDs[@]}";
		do
			names[$index]=$(xdotool getwindowname ${IDs[$index]})
		done

		sel_index="$( printf '%s\n' "${names[@]}" | rofi -dmenu -p "Show" -i -format i -width 25)"

		if test "$sel_index" != "";
		then
			#xdotool windowactivate ${IDs[$sel_index]}
			xdotool windowmap ${IDs[$sel_index]}
			sed -i "/${IDs[$sel_index]}/d" $list_path
		fi
	fi
fi
