#! /bin/bash

toggle_list=/tmp/xtoggle_list

# $1 --> name

wid=$(wmctrl -lx | grep -i $1 | awk '{ print $1 }')
echo $wid

if [ "$?" != "0" ];
then
	exec $1
else
	status=$(xwininfo -id $wid | grep "Map State")
	if [[ "$status" == *"IsViewable"* ]];
	then
		xdotool windowunmap $wid
	else
		xdotool windowmap $wid
	fi
fi
